site_name: LP-Cloud
site_url: https://arnwolff.github.io/LP-Cloud/
theme:
  name: material
nav:
  - Accueil: index.md
  - Outils DevOps: 
    - Les outils DevOps: outils-devops/outils-devops.md
    - Git: outils-devops/git.md